backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "src/assets/images/articles/" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images/articles/" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true

display_url: https://gulacsiandras.blog

collections:
  - name: "cikk" # Used in routes, e.g., /admin/collections/blog
    label: "Cikk" # Used in the UI
    folder: "src/posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "A cikk címe", name: "title", widget: "string"}
      - {label: "A publikálás dátuma", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "A cikk kivonata", name: "excerpt", widget: "text"}
      - {label: "A borítókép", name: "coverImage", widget: "image"}
      - {label: "A hozzászólások engedélyezése", name: "comments", widget: "boolean", default: true}
      - {label: "Témakör", name: "topic", widget: "select", options: ["éghajlatváltozás", "energetika", "erőforrások", "gmo", "mezőgazdaság", "pszichológia", "túlnépesedés", "egyéb"], multiple: false}
      - {label: "A cikk szövege", name: "body", widget: "markdown"}
